### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by xmha97**

### CODE REVIEW

**Comment by Rootzpower** [comment]
Sorry about the question but why you want to add that scripts like "script.module.simpleeval" or "script.module.unidecode" and the others ?

**Comment by xmha97** [comment]
"script.module.unidecode" and "script.module.simpleeval" are dependency for "script.skinshortcuts"

"script.skinshortcuts" is a dependency for "skin.aura"

In any case, to use this skin, you must have all of these packages installed.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="script.skinshortcuts" name="Skin Shortcuts" version="2.0.0" provider-name="BigNoid, marcelveldt, SiLVO">
    <requires>
        <import addon="xbmc.python" version="3.0.0"/>
        <import addon="script.module.unidecode" version="1.1.1+matrix.2"/>
        <import addon="script.module.simpleeval" version="0.9.10"/>
    </requires>
```

**Comment by Rootzpower** [comment]
But dependencies will be installed with add-on
For example, if you install script.module.metadatautils the add-on go get automatically:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="script.module.metadatautils"
       name="Metadata and Artwork module"
       version="1.0.43"
       provider-name="marcelveldt and others">
    <requires>
		<import addon="xbmc.python" version="3.0.0"/>
        <import addon="script.module.requests" version="2.9.1"/>
        <import addon="script.module.beautifulsoup4" version="4.9.3" />
        <import addon="script.module.thetvdb" version="1.0.29" />
        <import addon="script.module.musicbrainz" version="0.7.0"/>
        <import addon="script.module.simplecache" version="2.0.2"/>
        <import addon="script.module.arrow" version="0.15.5"/>
    </requires>
```

You can see all add-ons you need here:
https://github.com/kodi-community-addons/repository.marcelveldt

Kodi community addons update it to matrix

**Comment by xmha97** [comment]
I do not know why but I had to install the dependencies manually.
I did not have the `repository.marcelveldt`

**Comment by kcook98765** [comment]
Yes, the dependencies should be pulled in by the Addon that requires them, so I'm not going to address that in this repository. Thank You.

**Pull request closed without merging**
